### ISSUE TITLE
Problems downloading YouTube video

### ISSUE THREAD

**Issue by M4x1mumReZ** [Korozin/PyRSS-YouTube-Client#2]
I am running Windows 11 with Python 3.10.8. Whenever I try to download a video, I get the following error message in the terminal.

`'yrs' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by Korozin** [comment]
Uhhhh I'm not sure if YRS (youtube-rss-subscriber) works on Windows or not. I only use Linux so some commands might not be supported.

I can try and fish out an old laptop that I know has Windows and troubleshoot there.

**Comment by M4x1mumReZ** [comment]
I suppose that's probably why.

**Comment by Korozin** [comment]
So YRS does work on Windows. I tried it on the Windows Laptop and it works perfectly (after fixing the Auto-Install lol)

Try the WindowsVersion and see if that works for you. If not then that means your Python PATH might not be properly set up since YRS installs within a specific Path. Either that or WIndows 11 is just weird since I did this on Windows 10.

Did this on a COMPLETELY fresh Python install, got the installer from [here](https://www.python.org/ftp/python/3.10.8/python-3.10.8-amd64.exe) and checked `Add Python.EXE to PATH`

Then ran `PyRSS.py` immediately after and it worked fine.

**Comment by M4x1mumReZ** [comment]
Okay. I did a full re-install of Python and disabled application execution alliases through the 'System Settings' and I now don't get that error Except that now whenever I try to download a video or display a channel's videos, it tells me that it couldn't find the given video/channel ID.

![issue](https://user-images.githubusercontent.com/118238066/202369235-fd4a88e5-f1ae-462b-82a1-cebbe0f711b1.jpg)

**Comment by Korozin** [comment]
Ah yeah you have to be actually Subscribed to a channel to download any videos from it. Since it's reading directly from a .yml file and only pulls from the specific RSS Feeds you're subscribed to.

I could just change it to use youtube-dl instead so you can download globally as well since Yrs uses youtube-dl for some of the download processes. Would only need to change 1 line.

**Comment by Korozin** [comment]
Reflected the changes in the latest version.

Also included a .EXE build of the Script, I haven't tested in in full myself but the encoding seems to be fine. If you can tell me how well that works it'd be appreciated.

**Comment by M4x1mumReZ** [comment]
Everything works now. Closed.
